### PR TITLE
Add basic tests + Travis CI integration

### PR DESCRIPTION
**Pull request by ptondereau**
I've provided basic tests cases for laravel's service provider and support for integration in [Travis CI](https://travis-ci.org/).

You should also use [StyleCI](https://styleci.io/) for linearise editing style between contributors.

Tests are OK without Socialite but fail with it...

Deep tests for socialite driver are left to do.

### CODE REVIEW

**Comment by FaaPz** [comment]
Thank you for your contribution @ptondereau! We'll merge it as soon *you* think it's good enough.

Also, do you recommend placing anything else other than `preset: laravel` into the `.styleci.yml` file?

**Comment by ptondereau** [comment]
It's already good enough to go with it. It's just need more tests/mocking with socialite.
For styleCI, you don't need a file because it handle it automatically  ;)

**Comment by RicardoJ** [comment]
This is a very nice contribution to this module. Thank you @ptondereau! 👍

**Comment by ptondereau** [comment]
Thanks. Don't forget to use travis and styleci

**Pull request merged**
