### PR TITLE
Add Laravel 5.4 support

### PR DESCRIPTION
**Pull request by petericebear**
## Description
Support for Laravel 5.4

### CODE REVIEW

**Comment by willemstuursma** [comment]
Thanks @petericebear. I've updated the master to fix the failing CI build and also make some improvements to our `composer.json`. Could you have a try with `dev-master` and report back? If it works, we'll release a new version.

**Comment by petericebear** [comment]
dev-master worked out for me and Laravel 5.4

**Comment by yooouuri** [comment]
Changing to dev-master also does the trick for me.

One question (maybe this is not the best place to ask), where is ```dev-master``` defined? I mean there is only one branch and in the composer.json version is ```"version": "1.3.0"```.

**Comment by petericebear** [comment]
@yooouuri It is a bit off-topic, but it is a composer thing. Dayle Rees wrote a book about it: https://leanpub.com/composer-php. Where the versions stands, there you can adjust to dev-master for instance.

**Comment by willemstuursma** [comment]
We've released the new version 1.4.0.

**Pull request closed without merging**
