### PR TITLE
Add method to get an access token with a refresh token

### PR DESCRIPTION
**Pull request by Robertbaelde**
## Description
A method which let a user obtain an access token with a valid Refresh token 

## Motivation and Context
This fixes issue https://github.com/mollie/laravel-mollie/issues/22, all credits go to @gtapps

### CODE REVIEW

**Comment by Robertbaelde** [comment]
Looks like the tests needs a valid mollie token?

**Comment by FaaPz** [comment]
@Robertbaelde No, it was a broken testcase. I've just fixed it, and restarted your build. It has passed now. 😄 

Thank you for preparing this PR! Unfortunately it is not yet complete. The `Authorization` header is missing and the `code` parameter in the _tokenfields_ array is unnecessary. If you would like to change these, we'll merge this PR.

**Comment by Robertbaelde** [comment]
@FaaPz The Authorization header isn't needed right? Because you exchange a refresh token for a access token. The access token (ie the authorization) doesn't have to be valid in order to obtain a new one? 
I'll remove the code parameter

**Comment by FaaPz** [comment]
@Robertbaelde Oops, you're right. My bad. Only the `code` parameter change then. 😅

**Pull request merged**
