### PR TITLE
Added helper file/function for mollie() to \Mollie::api()

### PR DESCRIPTION
**Pull request by nickurt**
## Description
To cleanup the facade/method `\Mollie::api()` to just only a (helper)-function `mollie()`

## Motivation and Context
See above

## How Has This Been Tested?
tests/HelpersTest.php

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by sandervanhooft** [comment]
@nickurt Thanks! Seems like a breaking change to me?

**Comment by nickurt** [comment]
I don't see why.

You can still use the Laravel Facade way (`\Mollie::api()-> ... `), this only add a helper-file/function `mollie` which is a shorthand for the Laravel Facade `Mollie::api()-> ...`.

**Comment by sandervanhooft** [comment]
I thought there already is a 'mollie()' facade included currently which afaik should do exactly the same.

(Also, Laravel community favors facades over global helper methods.)

**Comment by nickurt** [comment]
Yeah, but my personal opinion is I didn't like the write it with `::api()` every time, that was my motivation to create this pull request

**Comment by sandervanhooft** [comment]
You're right! (OMG ;) )

Just tried it in an example project, there's no `mollie()` helper method. And I just looked it up, seems like helper methods are ok now. :)

I'm not sure about the way it's defined though, I'll look into the Laravel core how the default helpers are defined.

**Comment by nickurt** [comment]
An other possibility (about to remove `::api()` ..) is to clean-up/re-think about the diff aliases we register for the Mollie-stuff in the ServiceProvider

https://github.com/mollie/laravel-mollie/blob/2808396be75525906acf8bcdf4c805600e9c87c0/src/MollieServiceProvider.php

But changing something here, will be a breaking change, so we can only do this by the next-major version of this package ...

**Comment by sandervanhooft** [comment]
That's what I was thinking at first, but it would still require a `app(...)' call wrapper. Your helper solution is shorter.

I just finished exploring the Laravel source, your solution is perfectly in line with theirs.

Will merge.

Sorry for the Monday-morning-confusion on my end and thanks for the PR @nickurt!

A great way to start this week. :smiley:

**Comment by sandervanhooft** [comment]
Just released in `2.1.0`!

**Pull request merged**
